name: LightningCSS Build dengan Rust

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch, tag, or commit) to build'
        required: true
        default: 'branch'
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      RUST_TARGET: aarch64-linux-android
      NDK_VERSION: r28b
      MIN_SDK_VERSION: 26
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: parcel-bundler/lightningcss
          ref: ${{ github.event.inputs.ref }}
      
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: aarch64-linux-android
          toolchain: nightly
      
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          local-cache: true
          link-to-sdk: true

      - name: Setup NDK toolchain path
        run: |
          echo "PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
        
      - name: Install dependencies
        run: yarn install
      
      - name: Konfigurasi cargo untuk Android
        run: |
          mkdir -p ~/.cargo
          cat > .cargo/config.toml << EOF
          [target.${RUST_TARGET}]
          linker = "aarch64-linux-android${MIN_SDK_VERSION}-clang"
          ar = "llvm-ar"
          EOF

      - name: Build untuk Android
        run: |
          # Verify toolchain
          which aarch64-linux-android${MIN_SDK_VERSION}-clang
          which llvm-ar
          aarch64-linux-android${MIN_SDK_VERSION}-clang --version
        
          # Build
          RUSTFLAGS="-C strip=symbols -C codegen-units=1 -A unnecessary-transmutes"
          yarn build-release
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER: aarch64-linux-android${MIN_SDK_VERSION}-clang
          AR: llvm-ar

      - name: Find and verify binding
        id: find-binding
        run: |
          BINDING_PATH=$(find . -name "lightningcss.android-arm64.node" | head -n 1)
        
          if [ -z "$BINDING_PATH" ]; then
            echo "No binding file found! Build may have failed."
            exit 1
          fi

          echo "Found binding at: $BINDING_PATH"
          echo "binding_path=$BINDING_PATH" >> $GITHUB_OUTPUT
        
          # Get file size
          FILE_SIZE=$(stat -c%s "$BINDING_PATH")
          echo "Binding file size: $FILE_SIZE bytes"
        
          # Verify file type
          file "$BINDING_PATH"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lightningcss.android-arm64.node
          path: ${{ steps.find-binding.outputs.binding_path}}
          retention-days: 7
